#!/bin/bash

rm -rf ~/.vim

# Install Solarized color scheme.
mkdir -p ~/.vim/colors
pushd ~/.vim/colors
wget https://raw.githubusercontent.com/altercation/vim-colors-solarized/master/colors/solarized.vim
popd

# Install tcomment for easily commenting out code.
mkdir -p ~/.vim/pack/tml/start
pushd ~/.vim/pack/tml/start
git clone https://github.com/tomtom/tcomment_vim
popd

ln -sf $PWD/vimrc ~/.vimrc

ln -sf $PWD/bash_aliases ~/.bash_aliases
ln -sf $PWD/bashrc ~/.bashrc
ln -sf $PWD/bash_profile ~/.bash_profile

ln -sf $PWD/tmux.conf ~/.tmux.conf

ln -sf $PWD/zshrc ~/.zshrc

ln -sf $PWD/gitconfig ~/.gitconfig

if [ ! -e ~/.ssh ]; then
	mkdir ~/.ssh
fi

if [ ! -e ~/.oh-my-zsh ]; then
	git clone https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
fi
ln -sf $PWD/jingyue.zsh-theme ~/.oh-my-zsh/themes/jingyue.zsh-theme
