#!/bin/bash

ln -sf $PWD/vim ~/.vim
ln -sf $PWD/vimrc ~/.vimrc
ln -sf $PWD/bash_aliases ~/.bash_aliases
ln -sf $PWD/bash_profile ~/.bash_profile
ln -sf $PWD/bashrc ~/.bashrc
ln -sf $PWD/dir_colors ~/.dir_colors
ln -sf $PWD/tmux.conf ~/.tmux.conf
if [ -d ~/.config/fish ]; then
	ln -sf $PWD/config.fish ~/.config/fish/config.fish
fi
