# Prefix key
set -g prefix C-j

# Appearance
set-window-option -g window-status-format ' #I:#W '
set-window-option -g window-status-current-format '#[reverse] #I:#W '
set -g status-bg black
set -g status-fg white
set -g status-interval 1
set -g status-right ''
set-window-option -g automatic-rename on
set -g set-titles on

# Key bindings
bind-key -n M-t new-window -c "#{pane_current_path}"
bind-key -n 'M-{' previous-window
bind-key -n 'M-}' next-window
bind-key -n C-S-Left swap-window -d -t -1
bind-key -n C-S-Right swap-window -d -t +1
# Creates a key binding to reload the configuration file. It's equivalent to
# running `tmux source-file ~/.tmux.conf`.
bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"
# Make Escape behave instantly in Vim/neovim inside tmux.
# Prevent quick "Esc + key" sequences from being interpreted as Alt/Meta keys.
set -sg escape-time 0
 
# By default, it's xterm which doesn't work with certain escape keys.
set -g default-terminal "tmux-256color"

# tmux doesn't by default inherit the shell. Here, we tell tmux to use zsh when
# available; otherwise fall back to bash.
run-shell '
if command -v zsh >/dev/null 2>&1; then
  s="$(command -v zsh)"
else
  s="$(command -v bash)"
fi

# The default-command option in tmux defines the command executed when a new
# window or pane is created. By default, default-command is an empty string,
# which tells tmux to create a **login** shell using the shell specified in
# default-shell. I set default-command explicitly so tmux creates a
# **non-login** shell.
tmux set -g default-command "$s"
# default-shell might not be needed given default-command. Keep it here just to
# be safe.
tmux set -g default-shell "$s"
'

set -g history-limit 10000

# Enable Vi-style key bindings in copy mode
set-window-option -g mode-keys vi
